# Generated by Django 3.1.13 on 2021-10-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0005_auto_20211022_0222"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name="owner", old_name="plan", new_name="_plan",
                ),
                migrations.RenameField(
                    model_name="owner",
                    old_name="plan_auto_activate",
                    new_name="_plan_auto_activate",
                ),
                migrations.RenameField(
                    model_name="owner",
                    old_name="plan_provider",
                    new_name="_plan_provider",
                ),
                migrations.RenameField(
                    model_name="owner",
                    old_name="plan_user_count",
                    new_name="_plan_user_count",
                ),
                migrations.AlterField(
                    model_name="owner",
                    name="_plan",
                    field=models.TextField(
                        db_column="plan", default="users-free", null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="owner",
                    name="_plan_auto_activate",
                    field=models.BooleanField(
                        db_column="plan_auto_activate", default=True, null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="owner",
                    name="_plan_provider",
                    field=models.TextField(
                        choices=[("github", "Github")],
                        db_column="plan_provider",
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="owner",
                    name="_plan_user_count",
                    field=models.SmallIntegerField(
                        db_column="plan_user_count", default=5, null=True
                    ),
                ),
            ],
        )
    ]
