# Generated by Django 4.2.2 on 2023-07-31 16:41

from django.db import migrations

from utils.migrations import RiskyRunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_auto_20230731_1627"),
    ]

    operations = [RiskyRunSQL("DROP TRIGGER IF EXISTS branch_update ON branches")]
