# Generated by Django 3.2.12 on 2022-05-30 21:02

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0013_repository_repos_service_id_author"),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name="repository",
            name="repos_service_id_author",
        ),
        migrations.RunSQL(
            'CREATE UNIQUE INDEX CONCURRENTLY "repos_service_id_author" ON "repos" ("service_id", "ownerid");'
        ),
    ]
