# Generated by Django 3.2.12 on 2023-02-13 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_commit_commits_repoid_branch_state_ts"),
        ("labelanalysis", "0002_auto_20230208_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelanalysisrequest",
            name="base_commit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label_requests_as_base",
                to="core.commit",
            ),
        ),
    ]
